name: Contador HTML

on:
    schedule:
    - cron: '* 0 * * *'
    workflow_dispatch:

jobs:
  contSoma:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Contar os arquivos HTML
        run: |
          count=$(find . -name '*' | wc -l)
          echo "Existem $count arquivos neste repositório."
