name: Criar TXT

on:
  workflow_dispatch:

jobs:
      criarTxt:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Criar arquivo TXT com conteúdo
          run: echo "Este é o conteúdo do arquivo" > meu_arquivo.txt
