name: Data hora Push

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dt_hora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say dt_hora
        run: date
