name: Listagem de Arquivos
on: 
  workflow_dispatch:

jobs:
  lista-arquivos:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Listagem de todos os arquivos
        run: ls -R
