name: User Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  userPush:
    runs-on: ubuntu-latest

    steps:
 
      - name: User Push
        run: echo "Usuario do push é ${{ github.actor }}"
